# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1g4farm2ss1achwvkqdbiynpgif1b24dljggzckwywiia7bk6qq2";
    aarch64-linux = "1h913syxwb73hd8bkbsicncjggnd8fwwwr6pbl3gcvr3xzsj2p51";
    x86_64-darwin = "1v32m3akqx576kyg02wihx44aavjnz2rw8bdz9dkx17ycc16p5hv";
    aarch64-darwin = "1gknbz7fydnv33kqzd43j73wncwrzgmb3k3hzj77bvs16h1qxf5g";
  };

  urlMap = {
    x86_64-linux = "https://github.com/mailtrap/mailtrap-local/releases/download/v0.4.1/mailtrap-local_0.4.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/mailtrap/mailtrap-local/releases/download/v0.4.1/mailtrap-local_0.4.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/mailtrap/mailtrap-local/releases/download/v0.4.1/mailtrap-local_0.4.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/mailtrap/mailtrap-local/releases/download/v0.4.1/mailtrap-local_0.4.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "mailtrap-local";
  version = "0.4.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./mailtrap-local $out/bin/mailtrap-local
    ln -s mailtrap-local $out/bin/mailtrap-sendmail
  '';

  meta = {
    description = "Local email sandbox + catcher: SMTP + Web UI + JSON API in one binary";
    homepage = "https://github.com/mailtrap/mailtrap-local";
    license = lib.licenses.mit;
    mainProgram = "mailtrap-local";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
