# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1df61yvr7igh1discv0gx9v3bcn89q58xy7fj4n7w01kg95mqprd";
    aarch64-linux = "14ns842blh412krlf0zaki8cgnasa10gfqjyfw0s9wd2d87f9bzw";
    x86_64-darwin = "1wi6bhrznf2kvvq5h9daab1a1yhz953vmr24kk5f5kiia3mmhidf";
    aarch64-darwin = "1wzm60xb14l7rd2pxcqmc6drxw98nipdz212azd5gfjjxzc6jxsr";
  };

  urlMap = {
    x86_64-linux = "https://github.com/mailtrap/mailtrap-local/releases/download/v0.4.0/mailtrap-local_0.4.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/mailtrap/mailtrap-local/releases/download/v0.4.0/mailtrap-local_0.4.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/mailtrap/mailtrap-local/releases/download/v0.4.0/mailtrap-local_0.4.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/mailtrap/mailtrap-local/releases/download/v0.4.0/mailtrap-local_0.4.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "mailtrap-local";
  version = "0.4.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./mailtrap-local $out/bin/mailtrap-local
    ln -s mailtrap-local $out/bin/mailtrap-sendmail
  '';

  meta = {
    description = "Local email sandbox + catcher: SMTP + Web UI + JSON API in one binary";
    homepage = "https://github.com/mailtrap/mailtrap-local";
    license = lib.licenses.mit;
    mainProgram = "mailtrap-local";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
