# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1slbv8p52w76r7k2rkc65rrdf3p9dc9ilpvip9rwvnnjg89sqbir";
    aarch64-linux = "1ishyd5p6pxgy144f7a0hyk5k8c14sw9czy5bhgccp8r1blnkdi8";
    x86_64-darwin = "1p831kjs3854ck2ry8zhzak2xrjgf1w4333bwkq719zv2q5izj3s";
    aarch64-darwin = "1vjyl30lmrwzjxm1xzvc12mv8nmy53fqh1zgyjypf65p3zxxz952";
  };

  urlMap = {
    x86_64-linux = "https://github.com/mailtrap/mailtrap-local/releases/download/v0.3.0/mailtrap-local_0.3.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/mailtrap/mailtrap-local/releases/download/v0.3.0/mailtrap-local_0.3.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/mailtrap/mailtrap-local/releases/download/v0.3.0/mailtrap-local_0.3.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/mailtrap/mailtrap-local/releases/download/v0.3.0/mailtrap-local_0.3.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "mailtrap-local";
  version = "0.3.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./mailtrap-local $out/bin/mailtrap-local
    ln -s mailtrap-local $out/bin/mailtrap-sendmail
  '';

  meta = {
    description = "Local email sandbox + catcher: SMTP + Web UI + JSON API in one binary";
    homepage = "https://github.com/mailtrap/mailtrap-local";
    license = lib.licenses.mit;
    mainProgram = "mailtrap-local";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
